sudo: required
services:
  - docker

script:
  - docker build -t grafana .
  - docker run --name grafana -d grafana
  - docker ps -a
  - sleep 20
  - docker exec -it grafana ps -ef
  - docker exec -it grafana curl http://localhost:3000/
